# Generated by Django 4.2.13 on 2024-08-19 08:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0003_remove_product_price_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menuitem',
            name='unit',
        ),
    ]
