# Generated by Django 5.1.1 on 2024-10-09 06:26

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('canteen', '0004_remove_menuitem_unit'),
    ]

    operations = [
        migrations.AddField(
            model_name='menuitem',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='menuitem',
            name='unit',
            field=models.CharField(max_length=20),
            preserve_default=False,
        ),
    ]
