# Generated by Django 5.1.1 on 2024-10-09 07:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0005_menuitem_price_menuitem_unit'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menuitem',
            name='price',
        ),
    ]
